ocaml/ocamlfind

src/findlib/frontend.ml
This is simply to ease use of findlib with code that may (transitively) bring in
ppx_js_style, which requires explicit type annotation of ignored values:
https://github.com/janestreet/ppx_js_style#-allow-unannotated-ignores
Without this fix, errors such as the following occur with `ocamlfind ocamlopt
-linkpkg -package ppx_jane ...`:
```
File "/tmp/findlib_initl319a54.ml", line 1, characters 0-49:
1 | Findlib.record_package Findlib.Record_core "unix";;
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: Jane Street style: Toplevel expression are not allowed here.
```
=> Use let () around toplevel expression

site-lib-src/compiler-libs/META.in, src/findlib/META.in
See https://github.com/ocaml/ocaml/pull/10124
This is clearly not optimal, since it will force linking to the native
backend and dynlink even for bytecode mode ; is there a way to specify
`requires(byte)` and `requires(native)` ?
=> Provide for linking the native toplevel now exposed as 'ocamltoplevel.cmxa'

.gitignore, configure, findlib.files, opam, tools/extract_args/Makefile, tools/extract_args/extract_args.mll
It's always been possible to build OCaml without the Str library and since 4.08 it's even supported by `configure`. More importantly, as soon as `ocamldoc` leaves the OCaml distribution so will the Str library.
This PR:
- Updates the opam file to version 2.0 (referenced against the one in opam-repository).
- The version number in opam was "wrong" - I've updated it to "1.8.1.git" and also altered `configure` to take the version number from the opam file so that it isn't duplicated.
- Converts `tools/extract_args/extract_args.ml` into an ocamllex script (it produces identical output)
=> Update opam file to 2.0 (for pinning) and remove dependency on str

.gitignore, Makefile, Makefile.config.pattern, configure
This PR fixes two problems. Since 4.08 it's been possible to disable all of the "otherlibraries" individually (bigarray, unix, etc.) - it's always been possible to do by editing `Makefile.config`. `ocamlfind` _requires_ the Unix library, and this is now checked by `configure`.
However, it fixes a bigger problem, demonstrated by this `Dockerfile` (courtesy of @kit-ty-kate, as was nailing down the cause of this problem!):
```dockerfile
FROM ocaml/opam:debian-10-opam
RUN opam switch create numbug ocaml-base-compiler.4.05.0
RUN sudo apt-get install -yy m4
ENV OPAMPRECISETRACKING=1
RUN opam install -y num.0
RUN opam install -y ocamlfind
RUN opam exec -- ocamlfind query num
RUN opam reinstall -y ocamlfind
RUN opam exec -- ocamlfind query num
```
The problem occurs in opam because `ocamlfind` is …
=> Overhaul the detection of separately-installed packages

tools/extract_args/Makefile
Detected in https://github.com/ocaml/opam-repository/pull/18339#issuecomment-799731503
`$<` is non-standard Makefile and returns an empty string on BSDs
=> Fix BSD support

configure
This typo prevents labltk support from being detected.
=> Fix typo: labtk -> labltk

configure, mini/ocamlfind-mini, opam, src/bytes/Makefile, src/findlib/META.in, src/findlib/Makefile, src/findlib/frontend.ml
Closes #29 
`String.create` -> `Bytes.create`. Works even for very old ocaml versions (tested with 4.01.0) that do not provide the bytes type.
=> support for OCaml 5

src/findlib/findlib_config.mlp, src/findlib/fl_split.ml, src/findlib/frontend.ml
I also did a pull request to ocaml compiler to detect haiku/beos platforms. those new constants are consistant, and the change is innocuous to ocamlfind by the way.
=> Adding constants for BeOS/Haiku platforms

Makefile
dune has the base packages builtin so ocamlfind is not required. However, when a META file is present dune reverts back to it. In this case, a race condition can occure on packages that for example uses `threads.posix` and is built at the same time as ocamlfind is installed. Such package would fail on some rare circonstances if the META file was in the middle of being copied
=> Install META files for the standard OCaml distribution atomically

src/findlib/Makefile
I broke the long line with many files on it, into multiple lines.  I'd like to go further, and pull out all the CMIs and specify them with "*.cmi", same for mli files as "*.mli", but didn't make that change b/c felt I should stop already and see if this was OK with you.  Let me know if you're ok with the suggestion for going further, and I'll do so, update PR.
=> Export more cmis

src/findlib/topfind.ml.in
In #require command (via function load_deeply) check that no package
we're going to load defines the "error" variable, and if so, print out
the first one we encounter.  This can be used to check for conflicts
between packages.
=> In #require command (via function load_deeply) check that no package defines "error" variable

Makefile
running `make package-macosx` will say `zsh: permission denied: tools/make-package-macosx` in current form when a user is using zsh. I have added `sh` to the command so that the script can be properly run.
=> Run script using sh command

src/findlib/topfind.ml.in
Supersedes #39 and applies @dra27 suggestions. I'm opening a new PR because I don't have permission to push on @patricoferris's fork.
=> Make reading of `ocaml_stdlib` configuration lazy

src/findlib/Makefile
See https://discuss.ocaml.org/t/problem-installing-ocamlfind-on-latest-ocamlpro-alpine-docker-image/10147
=> Fix bug when installing with a system compiler (and without coreutils)

opam
This doesn't affect the 1.9.6 release (heck, I hope it only affects museum users!). opam packages ocamlfind 1.0.4 for the OCaml 3.07 switches, so it's "worth" having the lowerbound constraint 🙂
=> Reflect OCaml 3.08+ requirement in `opam` file

src/findlib/findlib.ml, src/findlib/fl_package_base.ml, src/findlib/frontend.ml
When compiling with a recent OCaml version (4.14.1 in this case) warning 6 is enabled which warns about function application without the label.
Example:
```
File "fl_package_base.ml", line 304, characters 22-40:
304 | 	 let pkg_ancestors = query_requirements predlist pkg in
^^^^^^^^^^^^^^^^^^
Warning 6 [labels-omitted]: label preds was omitted in the application of this function.
```
This commit adds the labels (and renames anonymous arguments to allow labels to match names wherever convenient).
=> Fix warning 6 (labels-omitted)

src/bytes/Makefile, src/findlib/Makefile
When '-cc' is specified to ocamlopt, the '-shared' option will not have effect[1].
Add OCAMLOPT_SHARED so that users can specify OCAMLOPT and OCAMLOPT_SHARED separately.
e.g.,
OCAMLOPT = "ocamlopt -verbose -cc '${CC}' -ccopt '--sysroot=${STAGING_DIR_TARGET} ${CFLAGS}' -cclib '${LDFLAGS}' -I +compiler-libs" OCAMLOPT_SHARED = "ocamlopt -verbose -cc '${CC} -shared' -ccopt '--sysroot=${STAGING_DIR_TARGET} ${CFLAGS}' -cclib '${LDFLAGS}' -I +compiler-libs"
This will avoid build failure when specifying '-cc'.
[1] https://discuss.ocaml.org/t/ocamlopt-has-problem-with-cc-and-i-dir-options-when-theyre-not-in-standard-location/13346/5
=> add OCAMLOPT_SHARED for genenrating .cmxs files

src/findlib/fl_split.ml
I submitted this PR several years ago (to the Gitlab repo), but the bug is still there. So another attempt.
=> '.' path triggers an unhandled exception on Windows

configure, tools/patch
`$ocamlpath` wasn't going through enough conversions in `configure` (one path is processed with `cygpath`, the other wasn't). Additionally, on Windows the PATH separator is `;` and so with Windows OCaml 5 this was breaking one of the sed calls in `tools/patch`, since that uses `;` as the sed parameter separator.
=> Fix configuration process on Windows

configure
The autodetection of whether `-opaque` and `-g` are supported by the compiler is broken since OCaml 5.2 (as debugged by @emillon in issue #78), because now `ocamlc -opaque` gives an error even though the `-opaque` flag is supported.
This patch changes the tested command to be `ocamlc -opaque -version` (which succeeds if `-opaque` is supported and fails if not, even on recent OCaml), and likewise for `-g`.
=> Fix autodetection of -opaque and -g

src/findlib/Makefile
I was looking to modify the Makefile and wondered what `.mml` is. It doesn't seem to be used and removing it didn't create any issues that I could see, hence this PR.
There is no `findlib.mml` nor does anything seem to create it or compile it, so it seems this is a leftover of some thread/vmthread code that doesn't exist anymore.
=> Remove `.mml` references

src/findlib/findlib_config.mlp, src/findlib/frontend.ml
Implements a fix for an [issue reported in Discuss](https://discuss.ocaml.org/t/14344).
The original example, given `a.ml`:
```ocaml
let x = Thread.self ()
```
is that this command (despite being incorrect) works in 3.x/4.x:
```console
$ ocamlfind ocamlopt -I +unix -I +threads -package threads -linkpkg unix.cmxa threads.cmxa a.ml
ocamlfind: [WARNING] Package `threads': Linking problems may arise because of the missing -thread or -vmthread switch
```
but in 5.x:
```console 
$ ocamlfind ocamlopt -I +unix -I +threads -package threads -linkpkg unix.cmxa threads.cmxa a.ml
File "a.ml", line 1:
Error: Cannot find file /home/dra/.opam/fix-threads-5.1.1/lib/ocaml/threads.cmxa
```
This command isn't directly fixable, as the fix to ensure that `threads.cmxa` is linked from …
=> Disable various parts of -thread handling for 5.x

doc/README.xml, src/findlib/fl_dynload.ml, src/findlib/fl_dynload.mli
Before this patch, `Fl_dynload.load_packages` will unconditionally call `Dynlink.loadfile` to load each particular compilation unit.
This works fine in almost all our scenarios, however when compiling Web Workers with JSOO, we have found that `Dynlink.loadfile` takes a very long time as it will compile `.cma` files to `.js`.
In the case of jsCoq and `coq-lsp` this compilation process is too heavy. Prior to us using `findlib`, we used to trap all calls from Coq to `Dynlink.loadfile`, and we used a pre-compiled `.js` version which was much much faster.
This patch makes it possible for users of `Fl_dynload.load_packages` to override the call to `Dynlink.loadfile` as to for example implement the above cache setup, or to do other kinds of instrumentations.
=> [fl_dynload] Allow overriding low-level module loader

configure
A compatibility check in the `configure` script when dealing with OCaml 5's preconfigured `META` files is failing in opam when _upgrading_ from ocamlfind 1.9.5.
The test is supposed to ensure that if `ocamlfind` has been configured with `-sitelib $(ocamlc -where)` then it doesn't add `ocamlc -where` to `ocamlpath` (this reflects OS-distributed ocamlfind, IIRC).
Rather than risking string comparison of paths, the test for whether `-sitelib` is `$(ocamlc -where)` is done by looking `${ocaml_sitelib}/stdlib/META`. Unfortunately, in an opam switch with OCaml 5 and ocamlfind 1.9.5 already installed, `-sitelib` is the `$(opam var lib)` and `${ocaml_sitelib}/stdlib/META` will be the ocamlfind 1.9.5 `META` causing this test to fail.
The effect is that this sequence:
```
opam switch create 5.0 …
```
=> Fix opam upgrade to ocamlfind 1.9.6 for OCaml 5.x

INSTALL, configure
I ran shellcheck on the configure script which suggested a lot of nice improvements, mostly about quoting and making sure spaces don't break the commands.
Other interesting improvements include removing variables that are never set (thus always empty, which made it work), so removing them makes it easier to see what is happening.
Edit: I also applied the `$?` suggestion since it makes the code a bit less fragile and fixed the POSIX compatibility, so it should be as portable as it was before.
=> Apply Shellcheck improvement suggestions

opam
cf. https://github.com/ocaml/opam-repository/pull/26864#pullrequestreview-2433196198.
The setup using an environment variable is clearly beneficial to Dune's experimental package management feature, but I don't think it's a good thing to turn on at present for _all_ opam-repository users (especially given both @MSoegtropIMC and @jonahbeckford's concerns). It causes `ocamlfind` to depend on the `OPAM_SWITCH_PREFIX` environment variable being correct, which at present it does not. Given that opam itself can't do any kind of caching or relocation (at least at present), it doesn't seem to bring any benefit with that increased brittleness.
cc @Leonidas-from-XIV - there are a couple of mechanisms available which could allow this option to be enabled explicitly by a user, if it would be helpful …
=> Don't enable the `-with-relative-paths-at` in opam

src/bytes/Makefile
=> set OCAMLOPT_SHARED when building "bytes" replacement
